package AdminClasses;


import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Hardeep
 */
public class EditEpisode extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditEpisode
     */
    private String path = "";
    ArrayList<String> alshownames = new ArrayList<>();
    String epid;

    public EditEpisode(int episode_id, String show) {
        initComponents();
        this.epid = episode_id + "";
        String[] split = show.split("~~");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/vod", "root", "system");
            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
            ResultSet rs = stmt.executeQuery("select * from episodes where episode_id='" + episode_id + "'");
            if (rs.next()) {
                String ename = rs.getString("episode_name");
                String ecover = rs.getString("episode_cover");
                String esquare = rs.getString("episode_square");
                String edesc = rs.getString("description");
                String evideopath = rs.getString("video_path");
                String eduration = rs.getString("duration");
                tfCover.setText(ecover);
                taDesc.setText(edesc);
                tfDur.setText(eduration);
                tfName.setText(ename);
                tfVideo.setText(evideopath);
                tfSquare.setText(esquare);
            }
            cbSelect.addItem(split[0]);
            alshownames.add(show);
            rs = stmt.executeQuery("select * from videos where category_name='TVSHOW' and video_id not in('" + split[1] + "')");
            while (rs.next()) {
                String showname = rs.getString("title");
                String showid1 = rs.getString("video_id");
                alshownames.add(showname + "~~" + showid1 + "~~");
                cbSelect.addItem(showname);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbSelect = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lbImage1 = new javax.swing.JLabel();
        lbImage2 = new javax.swing.JLabel();
        btCover = new javax.swing.JButton();
        btSquare = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDesc = new javax.swing.JTextArea();
        tfDur = new javax.swing.JTextField();
        btVidpath = new javax.swing.JButton();
        tfVideo = new javax.swing.JTextField();
        tfCover = new javax.swing.JTextField();
        tfSquare = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();

        setTitle("EDIT EPISODE");

        cbSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSelectItemStateChanged(evt);
            }
        });

        jLabel1.setText("Select Tv Show");

        jLabel2.setText("Episode Name");

        jLabel3.setText("Cover Photo");

        jLabel4.setText("Square Photo");

        jLabel5.setText("Description");

        jLabel6.setText("Duration");

        jLabel7.setText("Video Path");

        lbImage1.setText("cover photo");

        lbImage2.setText("square photo");

        btCover.setBackground(new java.awt.Color(255, 255, 255));
        btCover.setText("...");
        btCover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCoverActionPerformed(evt);
            }
        });

        btSquare.setBackground(new java.awt.Color(255, 255, 255));
        btSquare.setText("...");
        btSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSquareActionPerformed(evt);
            }
        });

        taDesc.setColumns(20);
        taDesc.setRows(5);
        jScrollPane1.setViewportView(taDesc);

        btVidpath.setBackground(new java.awt.Color(255, 255, 255));
        btVidpath.setText("...");
        btVidpath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVidpathActionPerformed(evt);
            }
        });

        btAdd.setBackground(new java.awt.Color(255, 255, 255));
        btAdd.setText("UPDATE EPISODE");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                                    .addComponent(tfSquare, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tfCover, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btCover)
                                                    .addComponent(btSquare)))
                                            .addComponent(tfDur, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbImage2, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                            .addComponent(lbImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btVidpath, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCover, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCover)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lbImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSquare)
                    .addComponent(lbImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSquare, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVidpath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSelectItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSelectItemStateChanged

    private void btCoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCoverActionPerformed
        JFileChooser fc = new JFileChooser();

        int ans = fc.showOpenDialog(this);
        if (ans == JFileChooser.APPROVE_OPTION) {
            File f1 = fc.getSelectedFile();
            tfCover.setText(f1.getPath());
            this.path = f1.getPath();
                        Image scaledInstance = null;
            Image scaledSquare = null;
        try{
           scaledInstance = ImageIO.read(f1).getScaledInstance(lbImage1.getWidth(),
                                lbImage1.getHeight(), Image.SCALE_SMOOTH);
           lbImage1.setIcon(new ImageIcon(scaledInstance));
        }catch(Exception e){
            e.printStackTrace();
        }    
       }
        //this.lbImage1.setIcon(new ImageIcon(path));
    }//GEN-LAST:event_btCoverActionPerformed

    private void btSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSquareActionPerformed
        JFileChooser fc = new JFileChooser();
        int ans = fc.showOpenDialog(this);
        if (ans == JFileChooser.APPROVE_OPTION) {
            File f1 = fc.getSelectedFile();
            tfSquare.setText(f1.getPath());
            this.path = f1.getPath();
                   Image scaledInstance = null;
            Image scaledSquare = null;
        try{
           scaledInstance = ImageIO.read(f1).getScaledInstance(lbImage2.getWidth(),
                                lbImage2.getHeight(), Image.SCALE_SMOOTH);
           lbImage2.setIcon(new ImageIcon(scaledInstance));
        }catch(Exception e){
            e.printStackTrace();
        }    
       }

    }//GEN-LAST:event_btSquareActionPerformed

    private void btVidpathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVidpathActionPerformed
        JFileChooser fc = new JFileChooser();

        int ans = fc.showOpenDialog(this);
        if (ans == JFileChooser.APPROVE_OPTION) {
            File f1 = fc.getSelectedFile();
            tfVideo.setText(f1.getPath());
        }
    }//GEN-LAST:event_btVidpathActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        String Title = tfName.getText();
        String Videopath = tfVideo.getText();
        String Coverpath = tfCover.getText();
        String Squarepath = tfSquare.getText();
        String Duration = tfDur.getText();

        int selectedIndex = cbSelect.getSelectedIndex();
        String show = alshownames.get(selectedIndex);
        String[] split = show.split("~~");
        String desc = taDesc.getText();
        if (Title.isEmpty() || Videopath.isEmpty()
                || desc.isEmpty() || Coverpath.isEmpty() || Squarepath.isEmpty() || Duration.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Fill all the Fields");
        } else {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/vod", "root", "system");
                Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                        ResultSet.CONCUR_UPDATABLE);
                ResultSet rs = stmt.executeQuery("select * from episodes where episode_id='" + epid + "'");
                if (rs.next()) {
                    rs.updateString("episode_name", Title);
                    rs.updateString("episode_cover", Coverpath);
                    rs.updateString("episode_square", Squarepath);
                    rs.updateString("tvshow_id", split[1]);
                    rs.updateString("Description", desc);
                    rs.updateString("duration", Duration);
                    rs.updateString("video_path", Videopath);
                    rs.updateRow();
                    JOptionPane.showMessageDialog(this, "Episode of " + split[0] + " updated Successsfully");
                    dispose();
                } else {
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btCover;
    private javax.swing.JButton btSquare;
    private javax.swing.JButton btVidpath;
    private javax.swing.JComboBox<String> cbSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbImage1;
    private javax.swing.JLabel lbImage2;
    private javax.swing.JTextArea taDesc;
    private javax.swing.JTextField tfCover;
    private javax.swing.JTextField tfDur;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfSquare;
    private javax.swing.JTextField tfVideo;
    // End of variables declaration//GEN-END:variables
}
